export const cardData = [{
        type: "عادی",
        offPercentage: 10,
        price: 290000,
        title: "سرویس ماشین های معمولی",
        quality: "کیفیت معمولی",
        noise: "کیفیت معمولی",
        timeLimite: "کیفیت معمولی",
        service: "کیفیت معمولی",
    },
    {
        type: "عادی",
        offPercentage: 15,
        price: 390000,
        title: "سرویس ماشین های کلاسیک",
        quality: "کیفیت عالی ",
        noise: "کم سرو صدا",
        timeLimite: "زمان نامحدود",
        service: "سرویس روزانه",
    },
    {
        type: "ویژه",
        offPercentage: 20,
        price: 490000,
        title: "سرویس ماشین های مدل بالا",
        quality: "کیفیت خیلی خفن",
        noise: "بی سرو صدا",
        timeLimite: "زمان نامحدود",
        service: "سرویس نامحدود",
    },
];